# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0074_auto_20170215_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='codi_postal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='frequencies',
            field=models.ManyToManyField(related_name='node', to='romani.Frequencia'),
        ),
        migrations.AlterField(
            model_name='node',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='pis',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='producte',
            name='dies_entrega',
            field=models.ManyToManyField(blank=True, to='romani.DiaEntrega'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='frequencies',
            field=models.ManyToManyField(blank=True, to='romani.Frequencia'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='romani.Node'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='convidats',
            field=models.ManyToManyField(blank=True, to='romani.Convidat'),
        ),
    ]
