# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0076_remove_contracte_prox_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='cancelat',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='entregat',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='contracte',
            name='cancelat',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='contracte',
            name='entregat',
            field=models.NullBooleanField(),
        ),
    ]
