# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0078_auto_20170317_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracte',
            name='darrera_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
