# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0079_contracte_darrera_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 31, 7, 6, 49, 68355, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
