# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0080_key_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='entradilla',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='mail',
        ),
    ]
