# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0081_auto_20170402_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='carrer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
