# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0082_auto_20170410_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='karma_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producte',
            name='karma_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='codi_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
