# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0084_auto_20170410_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='karma_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
