# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0085_auto_20170410_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipusproducte',
            name='productor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='romani.Productor'),
            preserve_default=False,
        ),
    ]
