# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0086_tipusproducte_productor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='dies_entrega',
        ),
        migrations.AddField(
            model_name='diaentrega',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dies_entrega', to='romani.Node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='productors',
            field=models.ManyToManyField(blank=True, to='romani.Productor'),
        ),
        migrations.AlterField(
            model_name='node',
            name='frequencies',
            field=models.ManyToManyField(to='romani.Frequencia'),
        ),
    ]
