# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0087_auto_20170424_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaentrega',
            name='date',
            field=models.DateField(),
        ),
    ]
