# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0088_auto_20170425_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='data_entrega_txt',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='darrera_entrega',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='data_entrega_txt',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='primera_entrega',
        ),
        migrations.RemoveField(
            model_name='producte',
            name='nodes',
        ),
        migrations.AddField(
            model_name='comanda',
            name='dia_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romani.DiaEntrega'),
        ),
        migrations.AddField(
            model_name='contracte',
            name='dies_entrega',
            field=models.ManyToManyField(blank=True, null=True, to='romani.DiaEntrega'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='dies_entrega',
            field=models.ManyToManyField(blank=True, related_name='productes', to='romani.DiaEntrega'),
        ),
    ]
