# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0089_auto_20170503_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productor',
            name='adjunt',
        ),
        migrations.AddField(
            model_name='adjunt',
            name='productor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='romani.Productor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='romani.Node'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='franjahoraria',
            name='final',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='franjahoraria',
            name='inici',
            field=models.TimeField(),
        ),
    ]
