# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0090_auto_20170505_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracte',
            name='dies_entrega',
            field=models.ManyToManyField(blank=True, to='romani.DiaEntrega'),
        ),
    ]
