# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 10:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('romani', '0091_auto_20170508_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producte',
            old_name='entradilla',
            new_name='text_curt',
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='cuerpo',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='node',
            name='responsable',
        ),
        migrations.AddField(
            model_name='node',
            name='responsable',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='productor',
            name='responsable',
        ),
        migrations.AddField(
            model_name='productor',
            name='responsable',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
