# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0092_auto_20170509_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracte',
            name='cancelat',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='entregat',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='freq_txt',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='convidats',
        ),
        migrations.AlterField(
            model_name='contracte',
            name='frequencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='romani.Frequencia'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='node',
            name='frequencies',
        ),
        migrations.AddField(
            model_name='node',
            name='frequencies',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='romani.Frequencia'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='producte',
            name='frequencies',
        ),
        migrations.AddField(
            model_name='producte',
            name='frequencies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='romani.Frequencia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Convidat',
        ),
    ]
