# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0093_auto_20170515_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipusproducte',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
