# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0094_auto_20170516_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaProduccio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dies_entrega', models.ManyToManyField(to='romani.DiaEntrega')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romani.Node')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romani.Productor')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('dia_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='romani.DiaProduccio')),
            ],
        ),
        migrations.RemoveField(
            model_name='producte',
            name='formats',
        ),
        migrations.AddField(
            model_name='tipusproducte',
            name='producte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='romani.Producte'),
        ),
        migrations.AddField(
            model_name='stock',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='romani.TipusProducte'),
        ),
    ]
