# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0095_auto_20170520_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='dies_entrega',
        ),
        migrations.AddField(
            model_name='productor',
            name='hores_limit',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='tipusproducte',
            name='dies_entrega',
            field=models.ManyToManyField(blank=True, related_name='formats', to='romani.DiaEntrega'),
        ),
        migrations.AlterField(
            model_name='diaproduccio',
            name='dies_entrega',
            field=models.ManyToManyField(related_name='dia_prod', to='romani.DiaEntrega'),
        ),
    ]
