# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0096_auto_20170520_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFormatStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus_stock', models.CharField(choices=[('0', 'Limit per produccio'), ('1', 'Limit per stock fix'), ('2', 'Sense Limit')], default='2', max_length=10)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='romani.DiaEntrega')),
            ],
        ),
        migrations.RenameField(
            model_name='tipusproducte',
            old_name='stock',
            new_name='stock_fix',
        ),
        migrations.RemoveField(
            model_name='tipusproducte',
            name='dies_entrega',
        ),
        migrations.AddField(
            model_name='diaformatstock',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dies_entrega', to='romani.TipusProducte'),
        ),
    ]
