# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0097_auto_20170525_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producte',
            old_name='adjunt',
            new_name='foto',
        ),
        migrations.AddField(
            model_name='node',
            name='privat',
            field=models.NullBooleanField(),
        ),
    ]
