# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0099_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='productors',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='romani.Productor'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='romani.Comanda'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='contracte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='romani.Contracte'),
        ),
    ]
