# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0101_auto_20170611_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_comanda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='dies_entrega',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='format',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='franja_horaria',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='lloc_entrega',
        ),
        migrations.RemoveField(
            model_name='contracte',
            name='producte',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='frequencies',
            new_name='frequencia',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='dia_entrega',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='franja_horaria',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='tipusproducte',
            name='stock_fix',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='comanda',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='contracte',
        ),
        migrations.AddField(
            model_name='comanda',
            name='frequencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='romani.Frequencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='node',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='romani.Node'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaformatstock',
            name='tipus_stock',
            field=models.CharField(choices=[('0', 'Limit per stock'), ('2', 'Sense Limit')], default='2', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_ini',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contracte',
        ),
        migrations.AddField(
            model_name='entrega',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='romani.Comanda'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='dia_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='romani.DiaEntrega'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='dia_produccio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='romani.DiaProduccio'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='franja_horaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romani.FranjaHoraria'),
        ),
        migrations.AddField(
            model_name='vote',
            name='entrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='romani.Entrega'),
            preserve_default=False,
        ),
    ]
