# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0103_auto_20170725_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lloc_entrega_perfil',
            new_name='lloc_entrega',
        ),
    ]
