# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0105_auto_20171015_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='karma_date',
        ),
        migrations.RemoveField(
            model_name='producte',
            name='karma_value',
        ),
        migrations.AddField(
            model_name='diaformatstock',
            name='hores_limit',
            field=models.IntegerField(default=48),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producte',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='Paraules Clau'),
        ),
    ]
