# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-26 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0107_auto_20171104_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='thumb',
            field=models.FileField(null=True, upload_to='productes/%Y/%m/%d'),
        ),
    ]
