# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-26 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0108_producte_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='thumb',
        ),
    ]
