# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-08 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0111_auto_20180115_0149'),
    ]
    operations = [
        migrations.AddField(
            model_name='producte',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lloc_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='romani.Node'),
        ),
    ]
