# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0112_auto_20181008_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
