# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-27 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0114_auto_20190126_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='nomes_seguent',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diaformatstock',
            name='tipus_stock',
            field=models.CharField(choices=[('0', 'Limit per stock'), ('1', 'Limit relatiu'), ('2', 'Sense Limit')], default='2', max_length=10),
        ),
    ]
