# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-16 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0114_auto_20180316_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='positiu',
            new_name='valor',
        ),
    ]
