# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-27 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0115_auto_20190127_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='frequencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romani.Frequencia'),
        ),
        migrations.AlterField(
            model_name='node',
            name='frequencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romani.Frequencia'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='frequencies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romani.Frequencia'),
        ),
    ]
