# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0115_auto_20180316_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='direccio',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
