# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-04 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romani', '0116_auto_20190127_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipusproducte',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
