"""
Django settings for labiadas project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+*w1wm^xq*3u8pybmcd*+w!vnk+wt%_y^m64os@i3a(i74#yp#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['0.0.0.0','*',
                 '79.137.39.201']

STATIC_ROOT = os.path.join(BASE_DIR, "romani/static/")

# Application definition

INSTALLED_APPS = (
    'romani',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'geoposition',
    'captcha',
    # 'notifications',
    'django_messages',
    # 'forum',
    'xlwt',
    'PIL',
    'rest_framework',
    'rest_framework_jwt',
    'corsheaders',
    # 'django_countries',
    # 'embed_video',
    # 'micawber.contrib.mcdjango',
    # 'tagulous',
    # 'forum',
    # 'autocomplete_light',
    # 'django_rest_framework_jwt',
    'django_registration',
    # Machina dependencies:
    'mptt',
    'haystack',
    'widget_tweaks',
    # Machina apps:
    'machina',
    'machina.apps.forum',
    'machina.apps.forum_conversation',
    'machina.apps.forum_conversation.forum_attachments',
    'machina.apps.forum_conversation.forum_polls',
    'machina.apps.forum_feeds',
    'machina.apps.forum_moderation',
    'machina.apps.forum_search',
    'machina.apps.forum_tracking',
    'machina.apps.forum_member',
    'machina.apps.forum_permission',
)




# SERIALIZATION_MODULES = {
#     'xml':    'tagulous.serializers.xml_serializer',
#     'json':   'tagulous.serializers.json',
#     'python': 'tagulous.serializers.python',
#     'yaml':   'tagulous.serializers.pyyaml',
# }






SITE_ID = 1

MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Machina
    'machina.apps.forum_permission.middleware.ForumPermissionMiddleware',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
)

ROOT_URLCONF = 'labiadas.urls'
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))


from machina import MACHINA_MAIN_TEMPLATE_DIR


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'romani/templates'), MACHINA_MAIN_TEMPLATE_DIR,],

        # 'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',
                # 'django_messages.context_processors.inbox',
                # 'labiadas.context_processors.notifications_user',
                'labiadas.context_processors.node_user',
                # 'labiadas.context_processors.foto_user',
                # Machina
                'machina.core.context_processors.metadata',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ]
        },
    },
]

WSGI_APPLICATION = 'labiadas.wsgi.application'

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'romani/templates'),
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

LOCALE_PATHS = ("locale/",)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ca'

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
def gettext_noop(s):
    return s
# gettext = lambda s: s
LANGUAGES = (
    ('ca', gettext_noop('Catalan')),
)


TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True



CORS_ORIGIN_ALLOW_ALL = True




STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(PROJECT_ROOT, 'static').replace('\\','/'),]





from machina import MACHINA_MAIN_STATIC_DIR

STATICFILES_DIRS = (
    # ...
    MACHINA_MAIN_STATIC_DIR,
)






SEND_EMAIL = True
ACCOUNT_ACTIVATION_DAYS = 30
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'lamassaxarxa@gmail.com'
EMAIL_HOST_PASSWORD = 'Pl4nes40'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

from django.urls import reverse_lazy
LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('coope')
LOGOUT_URL=reverse_lazy('login')
# REGISTRATION_OPEN = False

GEOPOSITION_GOOGLE_MAPS_API_KEY = ' AIzaSyA6f7rjDkdoQZFH3uy9UTOF7r8xxyOTAcE '

AUTHENTICATION_BACKENDS = (
    'romani.models.EmailModelBackend',
    'django.contrib.auth.backends.ModelBackend'
)




REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    )
}

import datetime

JWT_AUTH = {
    'JWT_RESPONSE_PAYLOAD_HANDLER':
        'romani.api.jwt_payload_handler',
    'JWT_ALLOW_REFRESH': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=150),
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    # 'JWT_AUTH_HEADER_PREFIX': '',
    # 'JWT_PAYLOAD_GET_USER_ID_HANDLER':
    # 'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',
}
#
#
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'machina_attachments': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp',
    },
}

# HAYSTACK_CONNECTIONS = {
#     'default': {
#         'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
#     },
# }

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(PROJECT_ROOT, 'whoosh_index'),
    },
}

MACHINA_FORUM_NAME = "La Massa Forum"

MACHINA_DEFAULT_AUTHENTICATED_USER_FORUM_PERMISSIONS = [
    'can_see_forum',
    'can_read_forum',
    'can_start_new_topics',
    'can_reply_to_topics',
    'can_edit_own_posts',
    'can_post_without_approval',
    'can_create_polls',
    'can_vote_in_polls',
    'can_download_file',
]